### ISSUE TITLE
AWS S3 IAM role support

### ISSUE THREAD

**Issue by nickjmv** [twuni/docker-registry.helm#60]
Hi,

We can't figure out how to let your chart work with S3 without setting the access and secret key. We just want to use the IAM role that is attached to our service account.

According to the official docker documentation, this should be possible by just omitting the access and secret keys. We also set the IAM permission described in the docs:

https://docs.docker.com/registry/storage-drivers/s3/

Are we missing something here or is your chart not built for this functionality?

Kind regards!

**Comment by surajnarwade** [comment]
In your values file, simply set:

```
serviceAccount.create = true
serviceAccount.name = <your-service-account-name>
serviceAccount.annotations = {
  "eks.amazonaws.com/role-arn" =  "IAM-role-ARN"
}
```

**Comment by nickjmv** [comment]
```
serviceAccount:
create: true
annotations:
  eks.amazonaws.com/role-arn: arn:aws:iam::XXXXXXXX:role/OUR_ROLE_NAME
```

Yes, we configured the above, but when starting the registry, we get permission errors.

**Comment by nickjmv** [comment]
Hi, I double checked the values from your comment to our configuration and they are exactly how you described them.
The pod does start for 1 minute and then it gets 503 status codes.

```
![image](https://user-images.githubusercontent.com/60742383/180943782-707720bd-7565-4c4e-962e-839066f0d24d.png)
```

**Comment by nickjmv** [comment]
I might have found something else.

When I explicitly set an accessKey and secretKey with the same permissions that I give my service account, it does work!
So I'm guessing that the helm chart is not working when needing to use an IAM role (service account). I read somewhere this could have something to do with an older AWS SDK that is used.

Can this be investigated?

**Comment by canterberry** [comment]
🤔 Maybe someone who is successfully using IRSA for S3 access can chime in here?

It sounds like one of a few things may be happening:

 1. The underlying [registry image](https://hub.docker.com/_/registry) doesn't support IRSA, or
 2. The IAM policy as described in the official registry documentation isn't adequate for your use case, or
 3. Something is interfering with either the auth token being mounted or the corresponding environment variable being set.

If you're able to launch a pod using the same service account provisioned/used by this Helm chart and that pod can upload a file to your S3 bucket, it would seem that the problem lies within the registry image itself, or in its pod configuration.

My understanding of IRSA is that it works by having a webhook that monitors for pods being launched using service accounts with the `eks.amazonaws.com/role-arn` annotation. That webhook notifies the `aws-auth` pod (which runs by default in EKS clusters) to request a *web identity token* for that role, then mounts that token into the pod at `/var/run/secrets/eks.amazonaws.com/serviceaccount/token` and sets a `AWS_WEB_IDENTITY_TOKEN_FILE` environment variable, for the pod, to that path. Then the pod launches as it normally would, and in the container, the AWS SDK picks it up from there by sniffing for that environment variable and using that token for auth.

So, next steps:

 1. With the Helm chart installed and the registry pod running (albeit lacking the necessary S3 permissions), can you shell into the container and check for the presence of a `AWS_WEB_IDENTITY_TOKEN_FILE` environment variable, and if present, whether you can read the file at the location indicated by its value?
 2. With that shell still launched, check for the presence of `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables. If these are present, even if they're empty, that could be a problem.
 3. If your S3 bucket is configured for encryption using KMS, make sure you have the relevant KMS permissions in your IAM policy. [example](https://gitlab.com/twuni/terraform/modules/aws-s3-bucket/-/blob/main/data.tf)

If all of that checks out, then if you could share the result of `helm template ...` when you're installing this chart (i.e: use the same `helm install` or `helm upgrade` command you'd use to install the chart, but use `helm template` instead), scrubbing/redacting any sensitive details, that would show what the chart "compiles down to" and better reveal anything we might have missed. If you're referencing any Kubernetes resources provisioned outside of this chart, like secrets, configmaps, or serviceaccounts, please share those as well (also redacting any sensitive details, of course).

**Comment by nickjmv** [comment]
Hi, thanks for your reaction.

> 1. With the Helm chart installed and the registry pod running (albeit lacking the necessary S3 permissions), can you shell into the container and check for the presence of a AWS_WEB_IDENTITY_TOKEN_FILE environment variable, and if present, whether you can read the file at the location indicated by its value?

Okay, I deployed the chart with the following values:
```
serviceAccount.create: true
serviceAccount.annotations.eks.amazonaws.com/role-arn: MY_ROLE_ARN
secrets.s3.accessKey: ""
secrets.s3.secretKey: ""
storage: s3
s3.region: MY_REGION
s3.regionEndpoint: s3.MY_REGION.amazon.aws.com
s3.bucket: MY_BUCKET_NAME (not arn, for clarification)
```

and when I execute in the registry pod and echo `AWS_WEB_IDENTITY_TOKEN_FILE` I get an output, a long random and weird string. Also, the path behind it is also readable:
```
/ $ ls -la /var/run/secrets/eks.amazonaws.com/serviceaccount
drwxr-sr-x    2 root     1000            60 Jul 28 04:58 ..2022_07_28_04_58_58.566258179
lrwxrwxrwx    1 root     1000            31 Jul 28 04:58 ..data -> ..2022_07_28_04_58_58.566258179
lrwxrwxrwx    1 root     1000            12 Jul 27 09:46 token -> ..data/token
```

> 2. With that shell still launched, check for the presence of AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables. If these are present, even if they're empty, that could be a problem.

When I describe the registry pod, these two environment variables are not there and when I try to echo them I also get no output. (The wrong ones I did on purpose to show any differences)

```
/ $ echo $AWS_ACCESS_KEY_ID

/ $ echo $AWS_ACCESS_KEY_IDD

/ $ echo $AWS_SECRET_ACCESS_KEY

/ $ echo $AWS_SECRET_ACCESS_KEYY

/ $
```

> 3. If your S3 bucket is configured for encryption using KMS, make sure you have the relevant KMS permissions in your IAM policy. [example](https://gitlab.com/twuni/terraform/modules/aws-s3-bucket/-/blob/main/data.tf)

My bucket is not configured with any encryption so this is no problem.

> If all of that checks out, then if you could share the result of helm template ...

[helm_template.txt](https://github.com/twuni/docker-registry.helm/files/9205700/helm_template.txt)

**Comment by canterberry** [comment]
Ah, your service account seems to be in a different namespace than the Helm chart's being installed to. That appears to be a defect in this chart. I'll create a PR for that right now.

**Comment by canterberry** [comment]
@nickjmv PR #65 is up, which should fix your issue by ensuring the ServiceAccount created by this chart has its namespace set consistently with that of the Deployment whose pod template references it.

**Comment by nickjmv** [comment]
Alright, great! Let's hope this will get merged soon so I can test it!

**Comment by canterberry** [comment]
> Alright, great! Let's hope this will get merged soon so I can test it!

You're welcome to test it now if you want, by installing the chart from a local copy of that branch:

```bash
$ git clone -b namespaced-service-account https://github.com/canterberry/docker-registry.helm my-registry
```

Just use the path where you cloned the chart instead of `twuni/docker-registry`. If that works for you, 🎉, with your approval I'll get that merged and shipped.

**Comment by nickjmv** [comment]
I just tested it but without any luck. I still receive the `level=error msg="response completed with error" err.code=unknown err.detail="s3aws: AccessDenied: Access Denied` error..

**Comment by canterberry** [comment]
> I just tested it but without any luck. I still receive the `level=error msg="response completed with error" err.code=unknown err.detail="s3aws: AccessDenied: Access Denied` error..

Thanks for trying. The missing namespace was the most glaring error, but there must be something else as well. 🤔 I'll investigate further as time permits and report back if I find something. In the meantime, at least you know you can get the registry working with S3 using an IAM user's access key. Maybe not ideal for your scenario, but it can at least work as a temporary workaround.

**Comment by epalchan** [comment]
This is related to- https://github.com/distribution/distribution/issues/3275
I've been able to resolve this by building the image directly from the source git repo, publishing it to a private repo and referencing it in the helm chart.

**Comment by canterberry** [comment]
#65 does not fix this, but GitHub triggered closing the issue automatically when that was merged. Reopening to track.

Thanks for the link, @epalchan! I've seen something like this before (where an unprivileged *container* can successfully and effortlessly impersonate the IAM identity of its host node), and it seems like a glaring and severe Kubernetes/EKS privilege escalation security vulnerability. If this is indeed the root cause, there must be a Kubernetes-layer solution.

**Comment by nickjmv** [comment]
Hi, I have been on leave for some time so I haven't been following everything here. But is the above a solution to the problem or just a workaround?
